services:
  nestar-api:
    container_name: nestar-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:3007
    volumes:
      - ./:/usr/src/nestar
    working_dir: /usr/src/nestar

    networks:
      - monorepo-network
    #For Production
    command: bash -c "npm install && npm run build && npm run start:prod"

  nestar-batch:
    container_name: nestar-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:3008
    volumes:
      - ./:/usr/src/nestar
    working_dir: /usr/src/nestar

    networks:
      - monorepo-network
    #For Production
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
